<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<WarningsAsErrors>false</WarningsAsErrors>
		<NoWarn>$(NoWarn);CS8618;CS8600;CS8602;CS8604;CS8625;CS8632</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Submance.Domain\Submance.Domain.csproj" />
	</ItemGroup>

</Project>